/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    'academic-years': AcademicYear;
    tags: Tag;
    rotations: Rotation;
    'annual-requirements': AnnualRequirement;
    'grad-requirements': GradRequirement;
    residents: Resident;
    'transfer-credits': TransferCredit;
    'avoidance-rules': AvoidanceRule;
    candidates: Candidate;
    schedules: Schedule;
    'schedule-assignments': ScheduleAssignment;
    'clinic-cycles': ClinicCycle;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'academic-years': {
      annualRequirements: 'annual-requirements';
    };
    tags: {
      gradRequirements: 'grad-requirements';
      annualRequirements: 'annual-requirements';
    };
    residents: {
      user: 'users';
      avoidanceRules: 'avoidance-rules';
      transferCredits: 'transfer-credits';
    };
    candidates: {
      schedules: 'schedules';
    };
    schedules: {
      scheduleAssignments: 'schedule-assignments';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'academic-years': AcademicYearsSelect<false> | AcademicYearsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    rotations: RotationsSelect<false> | RotationsSelect<true>;
    'annual-requirements': AnnualRequirementsSelect<false> | AnnualRequirementsSelect<true>;
    'grad-requirements': GradRequirementsSelect<false> | GradRequirementsSelect<true>;
    residents: ResidentsSelect<false> | ResidentsSelect<true>;
    'transfer-credits': TransferCreditsSelect<false> | TransferCreditsSelect<true>;
    'avoidance-rules': AvoidanceRulesSelect<false> | AvoidanceRulesSelect<true>;
    candidates: CandidatesSelect<false> | CandidatesSelect<true>;
    schedules: SchedulesSelect<false> | SchedulesSelect<true>;
    'schedule-assignments': ScheduleAssignmentsSelect<false> | ScheduleAssignmentsSelect<true>;
    'clinic-cycles': ClinicCyclesSelect<false> | ClinicCyclesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  password?: string | null;
  roles?: ('super-admin' | 'user')[] | null;
  username?: string | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'schedule-manager' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  /**
   * Link this user account to a Resident clinical record
   */
  resident?: (number | null) | Resident;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used for domain-based tenant handling
   */
  domain?: string | null;
  /**
   * Used for url paths, example: /tenant-slug/page-slug
   */
  slug: string;
  /**
   * If checked, logging in is not required to read. Useful for building public pages.
   */
  allowPublicRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residents".
 */
export interface Resident {
  id: number;
  tenant?: (number | null) | Tenant;
  firstName: string;
  lastName: string;
  displayName?: string | null;
  /**
   * The academic year they entered as PGY-1
   */
  startYear: number | AcademicYear;
  /**
   * The academic year they will be/were PGY-3. Usually startYear + 2, but may differ for leaves/transfers.
   */
  pgy3Year?: (number | null) | AcademicYear;
  /**
   * Login account associated with this resident
   */
  user?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Date the resident joined the program
   */
  joinDate?: string | null;
  /**
   * Date they left the program (null = still active)
   */
  leaveDate?: string | null;
  /**
   * Reason for departure
   */
  leaveReason?: ('graduated' | 'transferred_out' | 'dismissed' | 'on_leave') | null;
  avoidanceRules?: {
    docs?: (number | AvoidanceRule)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  transferCredits?: {
    docs?: (number | TransferCredit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Auto-generated placeholder for future-year scheduling. Cleaned up when real residents are enrolled.
   */
  isSynthetic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-years".
 */
export interface AcademicYear {
  id: number;
  startingYear: number;
  title?: string | null;
  /**
   * The official historical schedule for this academic year. Set automatically when a schedule is exported with the promotion checkbox.
   */
  canonicalSchedule?: (number | null) | Schedule;
  annualRequirements?: {
    docs?: (number | AnnualRequirement)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export interface Schedule {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  academicYear: number | AcademicYear;
  /**
   * The planning session this schedule belongs to. Null for historical/standalone schedules.
   */
  candidate?: (number | null) | Candidate;
  scheduleAssignments?: {
    docs?: (number | ScheduleAssignment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * X+Y clinic cycle configuration for this schedule. Cohort count = number of rows. Y = clinic weeks per cycle. X (inpatient block length) = (cohortCount × Y) − Y.
   */
  cycleConfig?: {
    /**
     * Y in the X+Y model: how many consecutive weeks each cohort spends in clinic per cycle. Most programs use 1 (4+1). Some use 2 (4+2 or 6+2).
     */
    clinicWeeksPerCycle?: number | null;
    /**
     * Each row is a clinic cycle cohort. Row order = cohort index (0-based). Add or remove rows to change the X+Y model (e.g. 5 rows + Y=1 → 4+1, 4 rows + Y=1 → 3+1).
     */
    cohorts?:
      | {
          /**
           * Residents assigned to this clinic cycle cohort.
           */
          residents?: (number | Resident)[] | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Groups of 3-year schedule planning sessions for real-time collaboration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidates".
 */
export interface Candidate {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * A descriptive name for this planning session, e.g. "May 2026 Planning Session".
   */
  title: string;
  /**
   * The first academic year of this 3-year planning horizon.
   */
  startingYear: number | AcademicYear;
  /**
   * Active = in progress. Finalized = year 1 was promoted to canonical. Archived = superseded.
   */
  status: 'active' | 'finalized' | 'archived';
  schedules?: {
    docs?: (number | Schedule)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual assignment cells within a schedule grid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-assignments".
 */
export interface ScheduleAssignment {
  id: number;
  tenant?: (number | null) | Tenant;
  schedule: number | Schedule;
  resident: number | Resident;
  /**
   * Week index (1–52) within the academic year
   */
  week: number;
  rotation: number | Rotation;
  /**
   * If set, the generator will not overwrite this assignment
   */
  locked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rotations".
 */
export interface Rotation {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Full clinical name, e.g. "Medical ICU"
   */
  title: string;
  /**
   * Short abbreviation (≤8 chars, A-Z and dashes only), e.g. MICU, W-RED. Displayed in the schedule grid.
   */
  codename: string;
  /**
   * Workload score (0 = no clinical work, 5 = maximum intensity)
   */
  intensity: number;
  /**
   * How many contiguous weeks the generator will try to schedule as a single block. Capped at X (inpatient span) for non-clinic rotations; fixed to Y (clinic weeks per cycle) for Clinic rotations. Leave blank to default to X.
   */
  preferredDuration?: number | null;
  /**
   * 0 = fully inpatient, 100 = fully ambulatory
   */
  outpatientPercentage: number;
  /**
   * Hue value (0–360). The frontend computes OKLCH colors from hue + intensity.
   */
  color?: string | null;
  /**
   * Eligible for Jeopardy/Backup coverage
   */
  isFlexible?: boolean | null;
  /**
   * If set, this rotation is a placeholder for the given tag category (e.g. "Elective", "Clinic"). The admin or resident must resolve it to a specific rotation.
   */
  isPlaceholder?: (number | null) | Tag;
  /**
   * First academic year this rotation is active
   */
  availableSince: number | AcademicYear;
  /**
   * Last academic year this rotation is active (blank = indefinite)
   */
  availableUntil?: (number | null) | AcademicYear;
  /**
   * Educational/audit buckets this rotation counts toward
   */
  tags?: (number | Tag)[] | null;
  /**
   * Staffing rules apply indefinitely until superseded by a newer block.
   */
  staffingConfigurations?:
    | {
        since: number | AcademicYear;
        minInterns?: number | null;
        maxInterns?: number | null;
        minSeniors?: number | null;
        maxSeniors?: number | null;
        /**
         * Drag rows to rank (top = most preferred).
         */
        preferences?:
          | {
              internCount: number;
              seniorCount: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Educational/audit bucket name, e.g. "Wards", "ICU", "Cardiology"
   */
  title: string;
  /**
   * Hint for what rotations apply to the tag
   */
  description?: string | null;
  /**
   * First academic year this tag is active
   */
  availableSince: number | AcademicYear;
  /**
   * Last academic year this tag is active (blank = indefinite)
   */
  availableUntil?: (number | null) | AcademicYear;
  gradRequirements?: {
    docs?: (number | GradRequirement)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  annualRequirements?: {
    docs?: (number | AnnualRequirement)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cumulative graduation requirements effective-dated to an academic year. Resolved against the resident’s matriculation year (latest rule where effectiveYear ≤ startYear).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grad-requirements".
 */
export interface GradRequirement {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Effective year: this rule applies to residents whose matriculation year is at or after this academic year, until a newer rule supersedes it.
   */
  academicYear: number | AcademicYear;
  tag: number | Tag;
  /**
   * Origin of this requirement (ACGME mandate, MHS policy, or program-specific)
   */
  source: 'acgme' | 'mhs' | 'program';
  /**
   * Hard floor (total weeks across residency)
   */
  minimum?: number | null;
  /**
   * Hard ceiling (total weeks across residency)
   */
  maximum?: number | null;
  /**
   * Soft goal (total weeks across residency)
   */
  ideal?: number | null;
  /**
   * Additional weeks targeted during PGY-1
   */
  pgy1Ideal?: number | null;
  /**
   * Additional weeks targeted during PGY-2
   */
  pgy2Ideal?: number | null;
  /**
   * Additional weeks targeted during PGY-3
   */
  pgy3Ideal?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Annual operational requirements effective-dated to an academic year. Resolved against the schedule year (latest rule where effectiveYear ≤ scheduleYear).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-requirements".
 */
export interface AnnualRequirement {
  id: number;
  tenant?: (number | null) | Tenant;
  academicYear: number | AcademicYear;
  tag: number | Tag;
  /**
   * Origin of this requirement (ACGME mandate, MHS policy, or program-specific)
   */
  source: 'acgme' | 'mhs' | 'program';
  /**
   * Hard floor (weeks). Violation if not met.
   */
  minimum?: number | null;
  /**
   * Hard ceiling (weeks). Violation if exceeded.
   */
  maximum?: number | null;
  /**
   * Soft goal (weeks). Closer is better, not a violation.
   */
  ideal?: number | null;
  /**
   * PGY-1 ideal weeks for this tag in this year
   */
  pgy1Ideal?: number | null;
  /**
   * PGY-2 ideal weeks for this tag in this year
   */
  pgy2Ideal?: number | null;
  /**
   * PGY-3 ideal weeks for this tag in this year
   */
  pgy3Ideal?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pairs of residents who should not be co-scheduled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avoidance-rules".
 */
export interface AvoidanceRule {
  id: number;
  tenant?: (number | null) | Tenant;
  resident: number | Resident;
  avoidedResident: number | Resident;
  updatedAt: string;
  createdAt: string;
}
/**
 * Educational credit a transfer-in resident brings from their prior program, per tag.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-credits".
 */
export interface TransferCredit {
  id: number;
  tenant?: (number | null) | Tenant;
  resident: number | Resident;
  /**
   * The educational bucket this credit counts toward
   */
  tag: number | Tag;
  /**
   * Number of weeks of credit from the prior program
   */
  weeks: number;
  /**
   * Name of the prior residency program
   */
  fromProgram?: string | null;
  /**
   * Free text for additional context
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each document is a clinic cycle cohort in the X+Y model. The number of cohorts × Y (clinic weeks per cycle) = Z (total cycle length). Add or remove cohorts to experiment with different X+Y configurations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-cycles".
 */
export interface ClinicCycle {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Cohort number (1-based). "Clinic Cycle 1" = clinic on the first week of the year.
   */
  number: number;
  /**
   * Auto-generated from cohort number
   */
  label?: string | null;
  /**
   * The academic year this cycle configuration applies to
   */
  academicYear: number | AcademicYear;
  /**
   * Residents assigned to this clinic cycle for this academic year
   */
  residents?: (number | Resident)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'academic-years';
        value: number | AcademicYear;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'rotations';
        value: number | Rotation;
      } | null)
    | ({
        relationTo: 'annual-requirements';
        value: number | AnnualRequirement;
      } | null)
    | ({
        relationTo: 'grad-requirements';
        value: number | GradRequirement;
      } | null)
    | ({
        relationTo: 'residents';
        value: number | Resident;
      } | null)
    | ({
        relationTo: 'transfer-credits';
        value: number | TransferCredit;
      } | null)
    | ({
        relationTo: 'avoidance-rules';
        value: number | AvoidanceRule;
      } | null)
    | ({
        relationTo: 'candidates';
        value: number | Candidate;
      } | null)
    | ({
        relationTo: 'schedules';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'schedule-assignments';
        value: number | ScheduleAssignment;
      } | null)
    | ({
        relationTo: 'clinic-cycles';
        value: number | ClinicCycle;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  password?: T;
  roles?: T;
  username?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  resident?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  slug?: T;
  allowPublicRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-years_select".
 */
export interface AcademicYearsSelect<T extends boolean = true> {
  startingYear?: T;
  title?: T;
  canonicalSchedule?: T;
  annualRequirements?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  availableSince?: T;
  availableUntil?: T;
  gradRequirements?: T;
  annualRequirements?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rotations_select".
 */
export interface RotationsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  codename?: T;
  intensity?: T;
  preferredDuration?: T;
  outpatientPercentage?: T;
  color?: T;
  isFlexible?: T;
  isPlaceholder?: T;
  availableSince?: T;
  availableUntil?: T;
  tags?: T;
  staffingConfigurations?:
    | T
    | {
        since?: T;
        minInterns?: T;
        maxInterns?: T;
        minSeniors?: T;
        maxSeniors?: T;
        preferences?:
          | T
          | {
              internCount?: T;
              seniorCount?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-requirements_select".
 */
export interface AnnualRequirementsSelect<T extends boolean = true> {
  tenant?: T;
  academicYear?: T;
  tag?: T;
  source?: T;
  minimum?: T;
  maximum?: T;
  ideal?: T;
  pgy1Ideal?: T;
  pgy2Ideal?: T;
  pgy3Ideal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grad-requirements_select".
 */
export interface GradRequirementsSelect<T extends boolean = true> {
  tenant?: T;
  academicYear?: T;
  tag?: T;
  source?: T;
  minimum?: T;
  maximum?: T;
  ideal?: T;
  pgy1Ideal?: T;
  pgy2Ideal?: T;
  pgy3Ideal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residents_select".
 */
export interface ResidentsSelect<T extends boolean = true> {
  tenant?: T;
  firstName?: T;
  lastName?: T;
  displayName?: T;
  startYear?: T;
  pgy3Year?: T;
  user?: T;
  joinDate?: T;
  leaveDate?: T;
  leaveReason?: T;
  avoidanceRules?: T;
  transferCredits?: T;
  isSynthetic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-credits_select".
 */
export interface TransferCreditsSelect<T extends boolean = true> {
  tenant?: T;
  resident?: T;
  tag?: T;
  weeks?: T;
  fromProgram?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avoidance-rules_select".
 */
export interface AvoidanceRulesSelect<T extends boolean = true> {
  tenant?: T;
  resident?: T;
  avoidedResident?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidates_select".
 */
export interface CandidatesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  startingYear?: T;
  status?: T;
  schedules?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  academicYear?: T;
  candidate?: T;
  scheduleAssignments?: T;
  cycleConfig?:
    | T
    | {
        clinicWeeksPerCycle?: T;
        cohorts?:
          | T
          | {
              residents?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-assignments_select".
 */
export interface ScheduleAssignmentsSelect<T extends boolean = true> {
  tenant?: T;
  schedule?: T;
  resident?: T;
  week?: T;
  rotation?: T;
  locked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-cycles_select".
 */
export interface ClinicCyclesSelect<T extends boolean = true> {
  tenant?: T;
  number?: T;
  label?: T;
  academicYear?: T;
  residents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}