/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    'academic-years': AcademicYear;
    tags: Tag;
    rotations: Rotation;
    'staffing-preferences': StaffingPreference;
    'annual-requirements': AnnualRequirement;
    'grad-requirements': GradRequirement;
    residents: Resident;
    'transfer-credits': TransferCredit;
    'avoidance-rules': AvoidanceRule;
    schedules: Schedule;
    'schedule-assignments': ScheduleAssignment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'academic-years': AcademicYearsSelect<false> | AcademicYearsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    rotations: RotationsSelect<false> | RotationsSelect<true>;
    'staffing-preferences': StaffingPreferencesSelect<false> | StaffingPreferencesSelect<true>;
    'annual-requirements': AnnualRequirementsSelect<false> | AnnualRequirementsSelect<true>;
    'grad-requirements': GradRequirementsSelect<false> | GradRequirementsSelect<true>;
    residents: ResidentsSelect<false> | ResidentsSelect<true>;
    'transfer-credits': TransferCreditsSelect<false> | TransferCreditsSelect<true>;
    'avoidance-rules': AvoidanceRulesSelect<false> | AvoidanceRulesSelect<true>;
    schedules: SchedulesSelect<false> | SchedulesSelect<true>;
    'schedule-assignments': ScheduleAssignmentsSelect<false> | ScheduleAssignmentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  password?: string | null;
  roles?: ('super-admin' | 'user')[] | null;
  username?: string | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  /**
   * Link this user account to a Resident clinical record
   */
  resident?: (number | null) | Resident;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used for domain-based tenant handling
   */
  domain?: string | null;
  /**
   * Used for url paths, example: /tenant-slug/page-slug
   */
  slug: string;
  /**
   * If checked, logging in is not required to read. Useful for building public pages.
   */
  allowPublicRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residents".
 */
export interface Resident {
  id: number;
  tenant?: (number | null) | Tenant;
  firstName: string;
  lastName: string;
  displayName?: string | null;
  /**
   * The academic year they entered as PGY-1
   */
  startYear: number | AcademicYear;
  /**
   * The academic year they will be/were PGY-3. Usually startYear + 2, but may differ for leaves/transfers.
   */
  pgy3Year?: (number | null) | AcademicYear;
  /**
   * Link to login account
   */
  user?: (number | null) | User;
  /**
   * Date the resident joined the program
   */
  joinDate?: string | null;
  /**
   * Date they left the program (null = still active)
   */
  leaveDate?: string | null;
  /**
   * Reason for departure
   */
  leaveReason?: ('graduated' | 'transferred_out' | 'dismissed' | 'on_leave') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-years".
 */
export interface AcademicYear {
  id: number;
  startingYear: number;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Educational/audit bucket name, e.g. "Wards", "ICU", "Cardiology"
   */
  title: string;
  /**
   * Hint for what rotations apply to the tag
   */
  description?: string | null;
  /**
   * Soft-delete flag. Retired tags are hidden from new requirement creation.
   */
  retired?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rotations".
 */
export interface Rotation {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Full clinical name, e.g. "Medical ICU"
   */
  title: string;
  /**
   * Machine identifier, e.g. MICU, RED. Used as the key in the scheduling engine.
   */
  codename: string;
  /**
   * Workload score (0 = no clinical work, 5 = maximum intensity)
   */
  intensity: number;
  /**
   * 0 = fully inpatient, 100 = fully ambulatory
   */
  outpatientPercentage: number;
  /**
   * Hex color or hue value for UI display
   */
  color?: string | null;
  /**
   * Eligible for Jeopardy/Backup coverage
   */
  isFlexible?: boolean | null;
  /**
   * Soft-delete flag
   */
  retired?: boolean | null;
  /**
   * Educational/audit buckets this rotation counts toward
   */
  tags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staffing-preferences".
 */
export interface StaffingPreference {
  id: number;
  tenant?: (number | null) | Tenant;
  title?: string | null;
  academicYear: number | AcademicYear;
  rotation: number | Rotation;
  /**
   * Number of interns (PGY-1) in this staffing configuration
   */
  internCount: number;
  /**
   * Number of seniors (PGY-2/3) in this staffing configuration
   */
  seniorCount: number;
  /**
   * Lower = more preferred. Rank 1 is the most desirable staffing combo.
   */
  preferenceRank: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Operational requirements for a specific academic year + tag. One entry per tag × year. Min/max apply uniformly across all PGY levels. PGY-specific ideals are soft goals for scoring.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-requirements".
 */
export interface AnnualRequirement {
  id: number;
  tenant?: (number | null) | Tenant;
  academicYear: number | AcademicYear;
  tag: number | Tag;
  /**
   * Origin of this requirement (ACGME mandate, MHS policy, or program-specific)
   */
  source: 'acgme' | 'mhs' | 'program';
  /**
   * Hard floor (weeks). Violation if not met.
   */
  minimum?: number | null;
  /**
   * Hard ceiling (weeks). Violation if exceeded.
   */
  maximum?: number | null;
  /**
   * Soft goal (weeks). Closer is better, not a violation.
   */
  ideal?: number | null;
  /**
   * PGY-1 ideal weeks for this tag in this year
   */
  pgy1Ideal?: number | null;
  /**
   * PGY-2 ideal weeks for this tag in this year
   */
  pgy2Ideal?: number | null;
  /**
   * PGY-3 ideal weeks for this tag in this year
   */
  pgy3Ideal?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cumulative graduation requirements tied to a class entry year. Tracks total weeks across the full residency for a given tag.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grad-requirements".
 */
export interface GradRequirement {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The class entry year (e.g. 2026 for the class starting July 2026)
   */
  startYear: number;
  tag: number | Tag;
  /**
   * Origin of this requirement (ACGME mandate, MHS policy, or program-specific)
   */
  source: 'acgme' | 'mhs' | 'program';
  /**
   * Hard floor (total weeks across residency)
   */
  minimum?: number | null;
  /**
   * Hard ceiling (total weeks across residency)
   */
  maximum?: number | null;
  /**
   * Soft goal (total weeks across residency)
   */
  ideal?: number | null;
  /**
   * Cumulative PGY-1 milestone ideal (weeks by end of PGY-1)
   */
  pgy1Ideal?: number | null;
  /**
   * Cumulative PGY-2 milestone ideal (weeks by end of PGY-2)
   */
  pgy2Ideal?: number | null;
  /**
   * Cumulative PGY-3 milestone ideal (weeks by end of PGY-3)
   */
  pgy3Ideal?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Educational credit a transfer-in resident brings from their prior program, per tag.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-credits".
 */
export interface TransferCredit {
  id: number;
  tenant?: (number | null) | Tenant;
  resident: number | Resident;
  /**
   * The educational bucket this credit counts toward
   */
  tag: number | Tag;
  /**
   * Number of weeks of credit from the prior program
   */
  weeks: number;
  /**
   * Name of the prior residency program
   */
  fromProgram?: string | null;
  /**
   * Free text for additional context
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pairs of residents who should not be co-scheduled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avoidance-rules".
 */
export interface AvoidanceRule {
  id: number;
  tenant?: (number | null) | Tenant;
  resident: number | Resident;
  avoidedResident: number | Resident;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export interface Schedule {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  academicYear: number | AcademicYear;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Individual assignment cells within a schedule grid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-assignments".
 */
export interface ScheduleAssignment {
  id: number;
  tenant?: (number | null) | Tenant;
  schedule: number | Schedule;
  resident: number | Resident;
  /**
   * Week index (1–52) within the academic year
   */
  week: number;
  rotation: number | Rotation;
  /**
   * If set, the generator will not overwrite this assignment
   */
  locked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'academic-years';
        value: number | AcademicYear;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'rotations';
        value: number | Rotation;
      } | null)
    | ({
        relationTo: 'staffing-preferences';
        value: number | StaffingPreference;
      } | null)
    | ({
        relationTo: 'annual-requirements';
        value: number | AnnualRequirement;
      } | null)
    | ({
        relationTo: 'grad-requirements';
        value: number | GradRequirement;
      } | null)
    | ({
        relationTo: 'residents';
        value: number | Resident;
      } | null)
    | ({
        relationTo: 'transfer-credits';
        value: number | TransferCredit;
      } | null)
    | ({
        relationTo: 'avoidance-rules';
        value: number | AvoidanceRule;
      } | null)
    | ({
        relationTo: 'schedules';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'schedule-assignments';
        value: number | ScheduleAssignment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  password?: T;
  roles?: T;
  username?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  resident?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  slug?: T;
  allowPublicRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-years_select".
 */
export interface AcademicYearsSelect<T extends boolean = true> {
  startingYear?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  retired?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rotations_select".
 */
export interface RotationsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  codename?: T;
  intensity?: T;
  outpatientPercentage?: T;
  color?: T;
  isFlexible?: T;
  retired?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staffing-preferences_select".
 */
export interface StaffingPreferencesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  academicYear?: T;
  rotation?: T;
  internCount?: T;
  seniorCount?: T;
  preferenceRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-requirements_select".
 */
export interface AnnualRequirementsSelect<T extends boolean = true> {
  tenant?: T;
  academicYear?: T;
  tag?: T;
  source?: T;
  minimum?: T;
  maximum?: T;
  ideal?: T;
  pgy1Ideal?: T;
  pgy2Ideal?: T;
  pgy3Ideal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grad-requirements_select".
 */
export interface GradRequirementsSelect<T extends boolean = true> {
  tenant?: T;
  startYear?: T;
  tag?: T;
  source?: T;
  minimum?: T;
  maximum?: T;
  ideal?: T;
  pgy1Ideal?: T;
  pgy2Ideal?: T;
  pgy3Ideal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residents_select".
 */
export interface ResidentsSelect<T extends boolean = true> {
  tenant?: T;
  firstName?: T;
  lastName?: T;
  displayName?: T;
  startYear?: T;
  pgy3Year?: T;
  user?: T;
  joinDate?: T;
  leaveDate?: T;
  leaveReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-credits_select".
 */
export interface TransferCreditsSelect<T extends boolean = true> {
  tenant?: T;
  resident?: T;
  tag?: T;
  weeks?: T;
  fromProgram?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avoidance-rules_select".
 */
export interface AvoidanceRulesSelect<T extends boolean = true> {
  tenant?: T;
  resident?: T;
  avoidedResident?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  academicYear?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-assignments_select".
 */
export interface ScheduleAssignmentsSelect<T extends boolean = true> {
  tenant?: T;
  schedule?: T;
  resident?: T;
  week?: T;
  rotation?: T;
  locked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}